trigger:
- main

pool:
  name: Default  # Replace with your self-hosted agent name if different

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet build
  displayName: 'Build project'

- script: dotnet pack --configuration Release
  displayName: 'Pack the library'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    publishVstsFeed: 'Lab4-DevOps/Lab4Feed'

